### ISSUE TITLE
Problem with  initBoard in server mode (no rendering ), "document is not defined"  with latest version  

### ISSUE THREAD

**Issue by robotiko** [jsxgraph/jsxgraph#184]
I'm using the lib for some server side computations in nodejs app, and I do init the board with:
 var board = JXG.JSXGraph.initBoard(null, {
  renderer: 'no',
  boundingbox: [0, 25, 25, 0],
  showCopyright: false,
  showNavigation: false
});
(taking from examples )

In current late night version since Jan 12, 2016 ,  I got a server crash with "document is not defined" error in lib loading that seems to come from   document"(window.document) inclusion in the lib. 
Dom document is undefined in the nodejs app (I have been using this code for several months) and seems to be a side effect of using  lodash to check it is a object or not, that  throws this error when document is not defined.

Any hint on how to use in server side now?

**Comment by alfredwassermann** [comment]
Can you tell me which version you used before?

**Comment by alfredwassermann** [comment]
OK, found the bug. Thanks for pointing this out. Fixed by 5fdd5ee38d49f8421b35e529d07785e4237a3189

**Comment by robotiko** [comment]
Thanks @alfredwassermann 
Late , but just in case. 
The previous working one I had was  0.99.4-dev

**Comment by robotiko** [comment]
Tried with latest night build (2016-01-17 22:12)
And this initBoard 	 
    board = JXG.JSXGraph.initBoard(null, {
      renderer: 'no',
      boundingbox: [0, 25, 25, 0],
      showCopyright: false,
      showNavigation: false
    });


Getting same result. 
Looking at the fix, is there a explicit need to set 'html' renderer?
Something that changes in the initBoard?

**Comment by alfredwassermann** [comment]
OK, now it should work.

**Comment by robotiko** [comment]
Thanks @alfredwassermann.
Unfortunately, it still doesn't work. 
Still  getting a server crash with "document is not defined" error in lib loading unless I load the  0.99.4-dev.

Thanks

**Comment by alfredwassermann** [comment]
OK, could fix another problem with renderer=='no'. Now, I tested it with nodejs...
Can you please give me feedback if it works?

**Comment by robotiko** [comment]
Hi @alfredwassermann , 
just tested with last night build (2016-01-18) and the issue persist. 
The issue is the same, it happens trying to load the lib in a controller to perform some computations.
The board init is the one added in previous comments.

**Comment by migerh** [comment]
Hi @robotiko 

I just did several successful test runs of examples/node/rendering.js with the latest fixes from @alfredwassermann and myself. Please test again with the next nightly build and let us know if this issue is resolved or still persists.


michael

**Comment by robotiko** [comment]
Hi @migerh , @alfredwassermann, 
just tested and seems to be working without issues. 
Finally solved!

Thanks a lot!

**Comment by alfredwassermann** [comment]
Great!
